### PR TITLE
SITES-825: Run drush rr immediately after importing the DB.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- Ensures that all PHP classes are registered to Drupal
- Ensures that all update hooks are found in new & old modules
- Ensures that modules that no longer exist are dropped from the registry as they may have an impact.

# Needed By (Date)
- Before migrating Iranian-studies

# Urgency
-  Medium

# Steps to Test

1. Check out this branch
2. Ensure the dev environment on acsf has the fix for guuid updates in capx.
3. migrate iranian-studies to dev

# Associated Issues and/or People
- SITES-825

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
We've had order-of-operations issues doing it this way in the past. If you don't run `updb` first, you get PDO exceptions on some sites.

`SITES-825` was to add a registry-rebuild _after_ the "Run drush updb a second time for recalcitrant sites" task.

We _may_ be able to try the registry-rebuild first if we add a `ignore_errors: "{% if ignore_updb_errors == 'TRUE' %}yes{% endif %}"`. The trick is remembering which site we had OOO issues with so that we can test adequately.

**Comment by sherakama** [comment]
I think the `drush rr` is safe with setting `ignore_errors: true` on the task and then running updb with a second rr and updb called for those that need it. Try and try again. In the past, some of my upgrade issues have been solved by running both drush rr and drush updb multiple times. It may not be sexy but it gets the job done.

**Comment by jbickar** [comment]
Sorry, `SITES-906` was to add a registry-rebuild after the "Run drush updb a second time for recalcitrant sites" task. I'll push some changes.

**Comment by jbickar** [comment]
_I WILL BEAT YOU INTO SUBMISSION_

**Comment by jbickar** [comment]
Take a 👀 and give it a 👍 , @sherakama.

**Comment by sherakama** [comment]
If at first, you don't succeed, rebuild the registry three times.

**Pull request merged**
