### PR TITLE
SITES-928

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- Split out the `sites.json` work into its own role
- Remove the `check-php` role from playbooks, as we rarely use it and it is slow

# Needed By (Date)
- 9.28.18

# Criticality
- How critical is this PR on a 1-10 scale? 9/10
- It will be critical for creating sites quickly enough on ACSF, and migrating them quickly

# Steps to Test

1. Check out this branch
2. Run `full-migration-playbook.yml` with [this inventory](https://github.com/SU-SWS/ansible-playbooks/files/2421302/PR58.txt)
3. Ensure that the vhosts are added as custom domains
4. Ensure that the caches are cleared
5. Ensure that the `check-php` role is skipped
6. Run `migration-sync-only-playbook.yml`
7. Ensure that the vhosts are added as custom domains
8. Ensure that the caches are cleared
9. Delete one or more of the sites
10. Run `acsf-site-setup-playbook.yml`
11. Ensure that the deleted sites are set up successfully

# Affected Projects or Products
- ACSF

# Associated Issues and/or People
- JIRA tickets:
    - https://stanfordits.atlassian.net/browse/SITES-928
    - https://stanfordits.atlassian.net/browse/SITES-925

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
I had some issues testing this so you can hold off until tomorrow.

**Comment by sherakama** [comment]
This works.

Got a few errors on the drush rr and updb portions but that is to be expected.

One additional environmental error to note:
```
failed: [academicskills] (item=cc all) => {"changed": true, "cmd": "drush @acsf.dev.cardinald7.academicskills cc all", "delta": "0:00:02.945193", "end": "2018-09-27 20:44:56.553980", "item": "cc all", "msg": "non-zero return code", "rc": 1, "start": "2018-09-27 20:44:53.608787", "stderr": "", "stderr_lines": [], "stdout": "Directory /mnt/gfs/home/cardinald7/.drush/cache/default exists, but      [error]\nis not writable. Please check directory permissions.\nfile_put_contents(/home/cardinald7/.drush/cache/default/8.1.17-annotationfiles-5-d1232d8ee7c08618f9c1446a768247c4.cache):  [warning]\nfailed to open stream: No such file or directory JSONCache.php:22", "stdout_lines": ["Directory /mnt/gfs/home/cardinald7/.drush/cache/default exists, but      [error]", "is not writable. Please check directory permissions.", "file_put_contents(/home/cardinald7/.drush/cache/default/8.1.17-annotationfiles-5-d1232d8ee7c08618f9c1446a768247c4.cache):  [warning]", "failed to open stream: No such file or directory JSONCache.php:22"]}
```

**Comment by sherakama** [comment]
Good to merge but I may take another pass at this later to try to reduce the processing overhead.

**Comment by jbickar** [comment]
OK I re-tested this and it appears to be working correctly. The one step that fails is Step 7, add vhost with `migration-sync-only-playbook.yml`, but I checked further back in the history and it does not appear that we were doing that previously. Thus, that's a different ticket.

**Pull request merged**
