### PR TITLE
SITES-900: skip stanford_person_views_update_7500()

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- Some sites fail on the stanford_person_views_update_7500() update hook. We want to selectively skip over that hook on a per-site basis.

# Needed By (Date)
- Whenever we do final cutover of the next round of H&S sites

# Criticality
- How critical is this PR on a 1-10 scale? 3/10
- It's the only thing blocking a number of sites from moving to ACSF

# Steps to Test

1. Check out this branch
2. Migrate linguistics with this inventory:
```
[products]
linguistics vhost="linguistics" skip_stanford_person_views_update_7500="TRUE"

[products:vars]
group_ids=671
```
3. See that it migrates successfully

# Affected Projects or Products
- H&S ACSF migrations

# Associated Issues and/or People
- JIRA ticket: https://stanfordits.atlassian.net/browse/SITES-900

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
I think I would prefer to refactor the upgrade hook so that it doesn't throw errors when something is awry, but rather, logs a few messages and carries on. That seems like more effort than this approach so perhaps merge and carry on.

**Comment by jbickar** [comment]
Ah, fair point. These contexts live in two separate modules, so it would require two separate update hooks. Let me ponder on that.

**Comment by jbickar** [comment]
Oops, my prior reply was to your comments on the `SITES-1177` PRs.

Yeah, one of the issues with the existing upgrade hooks is that they log a generic "Missing vocabulary or term" error regardless of which View they fail on. So it's hard to narrow down.

This approach masks the underlying issue. We're nearing the decision of whether to fish or cut bait on this.

**Comment by sherakama** [comment]
After review, skipping the views update and allowing the rest of the person updates happen is a bad idea. The feature gets in to a mixed state where some fields have been added, some were removed and the views are all over the place. After this I don't think it is a good idea to split the difference. We should either do all the updates and have them work, or do none of them at all.

If we skip the stanford_person updates for a few sites we will break our "known state" and will have to be extra cautious and provide extra handling when implementing future stanford_person upgrade hooks. Since I don't expect any futher active development on this feature I think we can allow this.

**Comment by jbickar** [comment]
So you are saying go with this approach rather than the one in https://github.com/SU-SWS/stanford_person/pull/81?

**Comment by sherakama** [comment]
Yes, and to expand it with skipping
* stanford_person_update_7500
* stanford_person_update_7501

**Comment by jbickar** [comment]
Hm, I have not seen `stanford_person_update7500()` or `stanford_person_update_7501()` fail.

**Comment by sherakama** [comment]
Aye, that is true, as the upgrade hooks have more error handling in them and are likely to finish. However, the changes in those two upgrade hooks are changes primarily to support the new views and don't really make sense to complete if we are not going to run the views updates as well. They have the potential to run without errors but could be destructive to the way the site works as it removes a taxonomy field that the 4.x views use.

**Comment by sherakama** [comment]
https://github.com/SU-SWS/stanford_person/blob/7.x-5.x-dev/stanford_person.install#L132

**Comment by jbickar** [comment]
This PR is essentially moot at this point, as we have no more ACSF migrations to do. I did use it for a number of H&S sites, so I would lean towards merging it for the sake of historical fidelity.

**Comment by jbickar** [comment]
_no more ACSF migrations to do_

**Comment by jbickar** [comment]
**_no more ACSF migrations to do_**

**Comment by jbickar** [comment]
_**NO MORE ACSF MIGRATIONS TO DO**_

**Pull request merged**
